/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack.view;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import pack.control.c_koneksi;
import pack.control.controllerToko;
import pack.model.m_toko;

/**
 *
 * @author Moklet
 */
public class home extends javax.swing.JFrame {
controllerToko ctoko;
List<m_toko>listdata = new ArrayList<>();
    /**
     * Creates new form home
     */
    public home(String user) {
        initComponents();
        ctoko = new controllerToko (this);
        ctoko.isiTable();
        nama_kasir1.setText(user);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtkode = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        nama_kasir6 = new javax.swing.JTextField();
        nama_kasir7 = new javax.swing.JTextField();
        nama_kasir8 = new javax.swing.JTextField();
        nama_kasir9 = new javax.swing.JTextField();
        cbjenis = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cbKategoriBrg1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nama_kasir1 = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        bersih = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cbKategoriBrg = new javax.swing.JComboBox<>();
        keluar1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel3.setText("Kode barang  :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 40, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel4.setText("Nama barang :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 80, 130, 30);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel5.setText("Kategori barang  :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 120, 170, 30);

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel6.setText("jenis Packaging   :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 160, 150, 30);
        jPanel2.add(txtharga);
        txtharga.setBounds(180, 200, 410, 30);

        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });
        jPanel2.add(txtkode);
        txtkode.setBounds(180, 40, 410, 30);
        jPanel2.add(txtnama);
        txtnama.setBounds(180, 80, 410, 30);
        jPanel2.add(nama_kasir6);
        nama_kasir6.setBounds(180, 80, 410, 30);
        jPanel2.add(nama_kasir7);
        nama_kasir7.setBounds(180, 80, 410, 30);
        jPanel2.add(nama_kasir8);
        nama_kasir8.setBounds(180, 80, 410, 30);
        jPanel2.add(nama_kasir9);
        nama_kasir9.setBounds(180, 80, 410, 30);

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pack", "Box" }));
        jPanel2.add(cbjenis);
        cbjenis.setBounds(180, 160, 410, 30);

        jLabel7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel7.setText("Harga  :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 200, 70, 30);

        cbKategoriBrg1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Baranglain" }));
        jPanel2.add(cbKategoriBrg1);
        cbKategoriBrg1.setBounds(180, 120, 410, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 60, 630, 290);

        jLabel2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel2.setText("Kasir  :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 10, 70, 30);

        nama_kasir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nama_kasir1ActionPerformed(evt);
            }
        });
        jPanel1.add(nama_kasir1);
        nama_kasir1.setBounds(80, 10, 190, 30);

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari);
        cari.setBounds(640, 370, 130, 30);

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(690, 90, 140, 40);

        ubah.setText("Ubah");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel1.add(ubah);
        ubah.setBounds(690, 140, 140, 40);

        bersih.setText("Bersihkan");
        bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihActionPerformed(evt);
            }
        });
        jPanel1.add(bersih);
        bersih.setBounds(690, 190, 140, 40);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(690, 240, 140, 40);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        Table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode barang", "Nama barang", "Kategori barang", "Jenis Packaging", "Harga"
            }
        ));
        jScrollPane2.setViewportView(Table1);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 800, 150);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 410, 820, 170);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 18)); // NOI18N
        jLabel1.setText(" Pencarian jenis barang :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 370, 190, 30);

        cbKategoriBrg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Baranglain" }));
        jPanel1.add(cbKategoriBrg);
        cbKategoriBrg.setBounds(210, 370, 410, 30);

        keluar1.setText("Keluar");
        keluar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluar1ActionPerformed(evt);
            }
        });
        jPanel1.add(keluar1);
        keluar1.setBounds(690, 290, 140, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 880, 600);

        setSize(new java.awt.Dimension(895, 631));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        ctoko.SimpanData();
        ctoko.isiTable();
    }//GEN-LAST:event_simpanActionPerformed

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
       ctoko.Ubah();
       ctoko.isiTable();
    }//GEN-LAST:event_ubahActionPerformed

    private void bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihActionPerformed
      ctoko.reset();
    }//GEN-LAST:event_bersihActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
       ctoko.hapus();
       ctoko.isiTable();
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
       ctoko.CariKategori();
        ctoko.isiTable();
    }//GEN-LAST:event_cariActionPerformed

    private void keluar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluar1ActionPerformed
         dispose();
    }//GEN-LAST:event_keluar1ActionPerformed

    private void nama_kasir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nama_kasir1ActionPerformed
       
    }//GEN-LAST:event_nama_kasir1ActionPerformed

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home(null).setVisible(true);
            }
        });
    }
public JTextField getTxtKode(){
        return txtkode;
    }
    public JTextField getTxtNama(){
        return txtnama;
    }
    public JTextField getTxtHarga(){
        return txtharga;
    }
    public JComboBox getCbKategori(){
        return cbKategoriBrg;
    }
    public JComboBox getCbJenis(){
        return cbjenis;
    }
    public JComboBox getCbCariKategori(){
        return cbKategoriBrg1;
    }
    public JButton getButtonHapus(){
        return hapus;
    }
    
    public JButton getButtonBersih(){
        return bersih;
    }
    public JButton getButtonSimpan(){
        return simpan;
    }
    public JButton getButtonUbah(){
        return ubah;
    }
    public JButton getButtonKeluar(){
        return keluar1;
    }
    public JTable getTableData(){
        return Table1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table1;
    private javax.swing.JButton bersih;
    private javax.swing.JButton cari;
    private javax.swing.JComboBox<String> cbKategoriBrg;
    private javax.swing.JComboBox<String> cbKategoriBrg1;
    private javax.swing.JComboBox<String> cbjenis;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton keluar1;
    private javax.swing.JTextField nama_kasir1;
    private javax.swing.JTextField nama_kasir6;
    private javax.swing.JTextField nama_kasir7;
    private javax.swing.JTextField nama_kasir8;
    private javax.swing.JTextField nama_kasir9;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    private javax.swing.JButton ubah;
    // End of variables declaration//GEN-END:variables
}
